name: Release Github

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
        contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build
      shell: pwsh
      run: ./build.ps1

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
